name: dynamic-reload
version: 0.1.0.0
license: BSD3
build-type: Simple
synopsis: Template app demonstrating dynamic code reloading with hint

executables:
  reloader:
    main: Main.hs
    source-dirs: app
    ghc-options: -Wall
    dependencies:
      - base >= 4.7 && < 5
      - hint
      - fsnotify
      - directory
      - filepath

